'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AmbDiff01.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1 \ansi \par \par \par \par \qc
        '''Liebe Versuchsperson, \par \par
        '''
        '''vielen Dank für Ihre Teilnahme an dieser Studie! \par \par \par
        '''
        '''Die Studie wird aus mehreren Aufgaben bestehen, die Sie nacheinander bearbeiten. \par \par
        '''Bitte lesen Sie die Instruktionen immer aufmerksam durch! \par \par \par \par
        '''
        '''Starten Sie mit dem ersten Teil der Studie, indem Sie den &quot;Weiter&quot;-Button drücken.
        '''}.
        '''</summary>
        Friend ReadOnly Property _0_mainInstr() As String
            Get
                Return ResourceManager.GetString("_0_mainInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _1_practiceYneg() As String
            Get
                Return ResourceManager.GetString("_1_practiceYneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _1_practiceYpos() As String
            Get
                Return ResourceManager.GetString("_1_practiceYpos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _2_experimentYneg() As String
            Get
                Return ResourceManager.GetString("_2_experimentYneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _2_experimentYpos() As String
            Get
                Return ResourceManager.GetString("_2_experimentYpos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _3_blockYneg() As String
            Get
                Return ResourceManager.GetString("_3_blockYneg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _3_blockYpos() As String
            Get
                Return ResourceManager.GetString("_3_blockYpos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _4_demoInstr() As String
            Get
                Return ResourceManager.GetString("_4_demoInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property _5_endInstr() As String
            Get
                Return ResourceManager.GetString("_5_endInstr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 1 0 1 0 1 0 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 0 0 1 1 1 0 1 0 0 0 1 1 1 1 0 0 1 1 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 1 1 0 0 0 0 1 1 0 1 1 0 1 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 0 1 1 0 0  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property BlockRandomisation() As String
            Get
                Return ResourceManager.GetString("BlockRandomisation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Leid Feind Streit Drohung Abschied Gefängnis Verbrechen.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Neg() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mut Lust Glück Freude Frieden Hoffnung Vertrauen Wochenende.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Pos() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpq Pgn Xbz Srj Fmhj Qpqd Tpfk Mqvl Hhwcj Pdvgw Rpxvk Rvhgl Sckrfl Snxwhv Wgwpkt Zcknhr Tkspzcg Lkxfstq Sskfblx Wmrzbnq Fkmrzdhs Mbdrfnmj Hvklxrhs Ldcfmxkz Lzhxpjtrf Vpwndzmsl Stglnwcbv Blvqxsjph Qmtcqswzfv Dpkbgrsvqj Jkvntxljph Nlvsngqpwx.
        '''</summary>
        Friend ReadOnly Property experimentPrime_Str() As String
            Get
                Return ResourceManager.GetString("experimentPrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BRUTAL EINSAM ELEND GRAUSAM ILLEGAL KRANK TRAGISCH TRAURIG.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Neg() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BELIEBT GENIAL GESUND LEBENDIG OPTIMAL PERFEKT SONNIG SUPER.
        '''</summary>
        Friend ReadOnly Property experimentTarget_Pos() As String
            Get
                Return ResourceManager.GetString("experimentTarget_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mord Angst Sklave.
        '''</summary>
        Friend ReadOnly Property practicePrime_Neg() As String
            Get
                Return ResourceManager.GetString("practicePrime_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kuss Idee Chance.
        '''</summary>
        Friend ReadOnly Property practicePrime_Pos() As String
            Get
                Return ResourceManager.GetString("practicePrime_Pos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lpqmf Pxbzqnh.
        '''</summary>
        Friend ReadOnly Property practicePrime_Str() As String
            Get
                Return ResourceManager.GetString("practicePrime_Str", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BOSHAFT KORRUPT UNGERECHT GEHÄSSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Neg() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Neg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GEDULDIG ZÄRTLICH HUMORVOLL FLEISSIG.
        '''</summary>
        Friend ReadOnly Property practiceTarget_Pos() As String
            Get
                Return ResourceManager.GetString("practiceTarget_Pos", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
